site_name: Apache Apex Documentation
site_favicon: favicon.ico
theme: readthedocs
pages:
- Apache Apex: index.md
- Development:
    - Development Setup: apex_development_setup.md
    - Applications: application_development.md
    - Packages: application_packages.md
    - Operators: operator_development.md
    - AutoMetric API: autometrics.md
    - Custom Control Tuples: control_tuples.md
    - Best Practices: development_best_practices.md 
- Operations:
    - Apex CLI : apex_cli.md
    - Security: security.md
- Compatibility: compatibility.md

